services:
  app:
    restart: unless-stopped
    env_file:
        - .env
    image: app
    build:
      dockerfile: ./Dockerfile
      context: ./
    environment:
      dsn: postgresql+asyncpg://postgres:password@pg/users
      rabbitmq_url: amqp://local:local@rabbitmq:5672/
      redis_url: redis://redis:6379
    ports:
      - "8000:8000"
    depends_on:
      pg:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    restart: unless-stopped
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
        - redis-data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ["redis-server"]

  rabbitmq:
    restart: unless-stopped
    image: rabbitmq:latest
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: local
      RABBITMQ_DEFAULT_PASS: local
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  pg:
    restart: unless-stopped
    image: postgres:latest
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d users"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis-data:
    driver: local
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local

configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management]."
